services:

  mysql:
    image: mysql:8.0

    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .

    container_name: springboot-app

    ports:
      - "8081:8081"

    depends_on:
      - mysql

volumes:
  mysql-data: